name: Create and publish Docker image

on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: [Linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: repo
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{github.repository}}

      # Get isolated repo name that is lowercase (not including organization)
      - name: Get lowercase repo name
        id: lowercase
        run: echo "::set-output name=lowercase::$(echo ${{ steps.repo.outputs.lowercase }} | cut -d'/' -f2)"

        # Create tag
      # - name: Create tag
      #   id: tagger
      #   uses: phish108/autotag-action@1.1.64
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN}}
      #     release-branch: master

      # Setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      # Login to Github Container Registry
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build Docker Image
      - name: Build Docker Image and push to Github Registry
        uses: docker/build-push-action@v4
        with:
          context: ./
          # If we are on beta, we want to tag the image as beta
          # else we want to tag it as latest
          tags: ghcr.io/${{ steps.repo.outputs.lowercase }}:${{ github.ref == 'refs/heads/master' && 'latest' }}
          push: ${{github.ref == 'refs/heads/master' }}
          cache-from: type=registry,ref=${{ steps.repo.outputs.lowercase }}:${{ github.ref == 'refs/heads/master' && 'latest' }}
          cache-to: type=inline

